[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
presale_contract = "82Jdd3gmbvTNCbu2SYGRNkvcESCYgaA6NHBUzbLaH5oh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
